import { useRouter } from 'next/navigation'
import MainLayout from '../components/MainLayout'



import { Inter } from 'next/font/google'
import { ContextProvider } from '../contexts/ContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({children}) {
  return (
    <>

       <html lang="en" className='h-full bg-gray-100'>
       <body className={`${inter.className} ${"h-full"}`}>
        <ContextProvider>
          <MainLayout>{children}</MainLayout>
        </ContextProvider>
        </body>
      </html>
    </>
  )
}

